@endpoint = http://localhost:37100

### show a warning message in vscode and get a choice selection
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "command": "custom.showWarningMessage", 
    "args": ["Make a choice", "Choice 1", "Choice 2"]
}

### list installed extensions
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "command": "custom.listInstalledExtensions" }

### get extension details
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "command": "custom.getExtensionInfo", "args": ["dpar39.vscode-rest-control"] }

### get current workspace file
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "command": "custom.workspaceFile" }

### get current workspace folders
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "command": "custom.workspaceFolders" }

### execute a command in active terminal
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "command": "custom.runInTerminal", "args": ["ls -la"] }


### Open file at line
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "command": "custom.goToFileLineCharacter", 
    "args": ["src/test/workspace1/demo.py", 5, 0]
}


### Start debugging with a custom configuration
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "command": "custom.startDebugSession",
    "args": [
        "${workspaceFolder}", 
        {
            "name": "Run sample.py",
            "type": "python",
            "request": "launch",
            "program": "demo.py",
            "console": "integratedTerminal",
            "justMyCode": true
        }
    ]
}

### Reveal line in current file
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "command": "revealLine",
    "args": [{"lineNumber": 15, "at": "center"}]
}

### Go to location (the hard way)
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "command": "editor.action.goToLocations",
    "args": [
        {
            "__type__": "Uri",
            "args": [
                "/abs/path/to/src/test/workspace1/demo.py"
            ]
        },
        {
            "__type__": "Position",
            "args": [4, 0]
        },
        [
            {
                "__type__": "Location",
                "args": [
                    {
                        "__type__": "Uri",
                        "args": [
                            "/home/ddiaz/vscode-rest-control/src/demo.py"
                        ]
                    },
                    {
                        "__type__": "Position",
                        "args": [9, 5]
                    }
                ]
            }
        ]
    ]
}

### Quick pick between 3 choices
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "command": "custom.showQuickPick",
    "args": [{
        "title": "Quick pick example",
        "defaultLabel": "Third Choice",
        "canSelectMany": false,
        "placeHolder": "Select an option",
        "items": [
            {
                "label": "First Choice",
                "detail": "some detail 1"
            },
            {
                "label": "Second Choice",
                "detail": "some detail 2"
            },
            {
                "label": "Third Choice",
                "detail": "some detail 3"
            }
        ]
    }]
}

### install an extension
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "command": "workbench.extensions.installExtension",
    "args": ["dpar39.vscode-taef-test-adapter"]
}

### uninstall an extension
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "command": "workbench.extensions.uninstallExtension",
    "args": ["dpar39.vscode-taef-test-adapter"]
}

### developer: reload window
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "command": "workbench.action.reloadWindow",
    "args": []
}
