### send a message to vscode
POST http://localhost:37100 HTTP/1.1
content-type: application/json

{"command": "custom.showErrorMessage", "args": ["Make a choice", "Choice 1", "Choice 2"]}

### list installed extensions
POST http://localhost:37100 HTTP/1.1
content-type: application/json

{"command": "custom.listInstalledExtensions", "args": []}

### execute command in terminal
POST http://localhost:37100 HTTP/1.1
content-type: application/json

{"command": "custom.runInTerminal", "args": "ls -la"}


### Open file at line
POST http://localhost:37100 HTTP/1.1
content-type: application/json

{"command": "custom.goToFileLineCharacter", "args": ["demo.py", 5, 0]}


### Start debugging with a custom configuration
POST http://localhost:37100 HTTP/1.1
content-type: application/json

{
    "command": "custom.startDebugSession",
    "args": [
        "${workspaceFolder}", 
        {
            "name": "Run sample.py",
            "type": "python",
            "request": "launch",
            "program": "demo.py",
            "console": "integratedTerminal",
            "justMyCode": true
        }
    ]
}

### Reveal line in current file
POST http://localhost:37100 HTTP/1.1
content-type: application/json

{
    "command": "revealLine",
    "args": [{"lineNumber": 15, "at": "center"}]
}

### Go to location (the hard way)
POST http://localhost:37100 HTTP/1.1
content-type: application/json

{
    "command": "editor.action.goToLocations",
    "args": [
        {
            "__type__": "Uri",
            "args": [
                "/home/ddiaz/vscode-rest-control/src/demo.py"
            ]
        },
        {
            "__type__": "Position",
            "args": [4, 0]
        },
        [
            {
                "__type__": "Location",
                "args": [
                    {
                        "__type__": "Uri",
                        "args": [
                            "/home/ddiaz/vscode-rest-control/src/demo.py"
                        ]
                    },
                    {
                        "__type__": "Position",
                        "args": [9, 5]
                    }
                ]
            }
        ]
    ]
}

### Quick pick between 3 choices
POST http://localhost:37100 HTTP/1.1
content-type: application/json

{
    "command": "custom.showQuickPick",
    "args": [{
        "title": "Quick pick example",
        "defaultLabel": "Third Choice",
        "canSelectMany": false,
        "placeHolder": "Select an option",
        "items": [
            {
                "label": "First Choice",
                "detail": "some detail 1"
            },
            {
                "label": "Second Choice",
                "detail": "some detail 2"
            },
            {
                "label": "Third Choice",
                "detail": "some detail 3"
            }
        ]
    }]
}