name: CI/CD pipeline
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "Build, test and release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install npm dependencies
        run: npm install
      
      - name: Run compile, formatting and linting checks
        run: npm run pretest

      - name: Build and run automation tests
        run: npm run test

      - name: Publish to VSCode Marketplace
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npx @vscode/vsce publish --allow-star-activation -p ${{ secrets.VSCE_PAT }}